apiVersion: v1
kind: Service
metadata:
  name: hellosvc
  namespace: default
  labels:
    app: hellosvc
spec:
  ports:
    - name: grpc
      port: 6001
      targetPort: 6001
    - name: rest
      port: 8001
      targetPort: 8001
  selector:
    app: hellosvc
