// Code generated by proto-gen-go-kit-transport. DO NOT EDIT.
// * Source: "printsvc/contract/contract/printsvc.proto"

package transport

import (
	"context"

	"printsvc/contract"
)

type UseCaseContract interface {
	PrintGreeting(ctx context.Context, request *contract.EmptyRequest) (response *contract.PrintGreetingResponse, err error) // (unary)
}

type transport struct {
	contract.UnimplementedPrintServiceServer
	UseCase UseCaseContract
}

func NewTransport(ctx context.Context, useCase UseCaseContract) *transport {
	return &transport{
		UseCase: useCase,
	}
}
