// Code generated by proto-gen-svc-transport. DO NOT EDIT.
// Folder	: "printsvc/contract"
// File		: "contract/printsvc.proto"

package transport

import (
	"context"

	"printsvc/contract"
	"go.elastic.co/apm/v2"
)

func (t transport) PrintGreeting(ctx context.Context, request *contract.EmptyRequest) (response *contract.PrintGreetingResponse, err error) {

	span, ctx := apm.StartSpan(ctx, "transport.PrintGreeting", "transport.internal")
	defer span.End()

	// * Bridging to usecase related method
	return t.UseCase.PrintGreeting(ctx, request)
}
