// Code generated by proto-gen-svc-interceptor.
// Folder	: "printsvc/contract"
// File		: "contract/printsvc.proto"

// * This file will not be regenerated, if it still exists.

package interceptor

import (
	"context"

	"google.golang.org/protobuf/reflect/protoreflect"
)

type Interceptor interface {
	Do(ctx context.Context, input protoreflect.ProtoMessage) error
	SetNext(Interceptor)
}
