apiVersion: v1
kind: Service
metadata:
  name: printsvc
  namespace: default
  labels:
    app: printsvc
spec:
  ports:
    - name: grpc
      port: 6002
      targetPort: 6002
    - name: rest
      port: 8002
      targetPort: 8002
  selector:
    app: printsvc