// Code generated by proto-gen-go-lib-contract . DO NOT EDIT.
// Source: "hellocln/contract"

package contract

import (
	"context"
	"google.golang.org/grpc/metadata"
)

type HelloService interface {
	GetDefaultMetadata(ctx context.Context) metadata.MD
	PrintHello(context.Context, metadata.MD, *PrintHelloRequest) (*PrintHelloResponse, error)
}

type MetadataRequestHelloService interface {
}
