// Code generated by proto-gen-go-kit-transport. DO NOT EDIT.
// * Source: "hellosvc/contract/contract/hellosvc.proto"

package transport

import (
	"context"

	"hellosvc/contract"
)

type UseCaseContract interface {
	PrintHello(ctx context.Context, request *contract.PrintHelloRequest) (response *contract.PrintHelloResponse, err error) // (unary)
}

type transport struct {
	contract.UnimplementedHelloServiceServer
	UseCase UseCaseContract
}

func NewTransport(ctx context.Context, useCase UseCaseContract) *transport {
	return &transport{
		UseCase: useCase,
	}
}
