// Code generated by proto-gen-svc-transport. DO NOT EDIT.
// Folder	: "hellosvc/contract"
// File		: "contract/hellosvc.proto"

package transport

import (
	"context"

	"hellosvc/contract"
	"go.elastic.co/apm/v2"
)

func (t transport) PrintHello(ctx context.Context, request *contract.PrintHelloRequest) (response *contract.PrintHelloResponse, err error) {

	span, ctx := apm.StartSpan(ctx, "transport.PrintHello", "transport.internal")
	defer span.End()

	// * Bridging to usecase related method
	return t.UseCase.PrintHello(ctx, request)
}
